#! /bin/bash

print_error() {
    # ANSI escape code for red text
    echo -e "\033[31m$1\033[0m"
}

RAMMAX=4g
WRITEMAX=4g

#docker-run-cpu-affinity --rm -v ~/sut-docker/xpdf-v4.00/baseline/:/out -v ~/outputs/pdfload-xpdf-v4.00_baseline-cmplog-$id:/fuzz_out -e FUZZING_ENGINE=libafl -e TIMEOUT=5m -t oss-base-runner run_fuzzer fuzz_pdfload
DUMMY=1
if [ -n "$1" ] ; then
    if [ "$1" == "--no-dummy" ] ; then
        DUMMY=0
    fi
fi

# cat /sys/devices/system/cpu/cpu0/topology/thread_siblings_list

get_cpu_siblings() {
    local cpuid=$1
    cat /sys/devices/system/cpu/cpu"$cpuid"/topology/thread_siblings_list
}

convert_to_minutes() {
    local time_str="$1"
    
    # Extract numeric part and unit
    local num="${time_str//[!0-9]/}"
    local unit="${time_str//[0-9]/}"

    # Convert num to an integer
    num=$((num))

    # Calculate minutes based on the unit
    case "$unit" in
        "h") minutes=$((num * 60)) ;;
        "m") minutes=$((num)) ;;
        "s") minutes=$((num / 60)) ;;
        *) echo "Invalid unit"; exit 1 ;;
    esac

    echo "$minutes"
}

perform_task() {
    fuzzing_engine=$1
    echo ""
    echo :----------------------
    echo : fuzzing_engine $1
    shift
    fuzzer=$1
    echo : fuzzer         $1
    shift
    fuzzer_dir=$1
    echo : fuzzer_dir     $1
    shift
    output_dir=$1
    echo : output_dir     $1
    shift
    runs=$1
    echo : runs           $1
    shift
    cor_start=$1
    echo : cor_start      $1
    shift
    timeout=$1
    echo : timeout        $1
    shift
    min_start=$1
    echo : min_start      $1
    echo :----------------------
    shift
    
    PRIVILEGED_FLAG=$([[ "$PRIVILEGED" == "1" ]] && echo "--privileged" || echo "")
    MULTIDESOCK_FLAG=$([[ "$MULTIDESOCK" == "1" ]] && echo "-e USE_MULTIDESOCK=1" || echo "-e USE_MULTIDESOCK=0")
    FUZZ_PORT_FLAG=$([[ "$FUZZ_PORT" != "0" ]] && echo "-e HFND_TCP_PORT=$FUZZ_PORT" || echo "")

    if [[ "$fuzzing_engine" != "afl" && "$fuzzing_engine" != "libafl" && "$fuzzing_engine" != "sgfuzz" ]]; then
        print_error "Error: The variable must be either 'afl', 'libafl' or 'sgfuzz' , not $fuzzing_engine."
        exit 1
    fi

    if [[ "$fuzzing_engine" == "afl" ]]; then
        timeout=$(convert_to_minutes $timeout)
        timeout=$(($timeout*60))
    fi

    ls $fuzzer_dir > /dev/null
    if [[ ! $? -eq 0 ]]; then
        print_error "ERROR $fuzzer_dir do not exist"
        exit 1
    fi
    ls $fuzzer_dir/$fuzzer > /dev/null
    if [[ ! $? -eq 0 ]]; then
        print_error "ERROR $fuzzer not present in $fuzzer_dir"
        exit 1
    fi
    # Loop from core_start to core_end
    for counter in $(seq 1 ${runs}); do
        minutes=$min_start
        core_id=$(($COUNTER_OFFSET+$counter+$cor_start-1))
        if [ $DUMMY == 1 ] ; then
            #dummy
            echo "docker run $PRIVILEGED_FLAG --cpuset-cpus="$(get_cpu_siblings $core_id)" --memory="$RAMMAX" -it --rm -v ${output_dir}-${counter}:/fuzz_out -v ${fuzzer_dir}:/out -e FUZZING_ENGINE=$fuzzing_engine $FUZZ_PORT_FLAG $MULTIDESOCK_FLAG -e TIMEOUT=$timeout -e OUTUID=$(id -u) -e OUTGID=$(id -g) -e CPU_ID_BIND=$core_id -t osvaldo/oss-base-runner run_fuzzer $fuzzer $*"
        else
            #real
            echo "docker run $PRIVILEGED_FLAG --cpuset-cpus="$(get_cpu_siblings $core_id)" --memory="$RAMMAX" --detach --rm -v ${output_dir}-${counter}:/fuzz_out -v ${fuzzer_dir}:/out -e FUZZING_ENGINE=$fuzzing_engine $FUZZ_PORT_FLAG $MULTIDESOCK_FLAG -e TIMEOUT=$timeout -e OUTUID=$(id -u) -e OUTGID=$(id -g) -e CPU_ID_BIND=$core_id -t osvaldo/oss-base-runner run_fuzzer $fuzzer $*"   | at now + $minutes min
        fi
    done
}

in_round_w_named_output (){
    sut_build_type=$1
    shift
    core_start=$1
    shift
    output_dir=$1
    shift

    perform_task $FUZZING_ENGINE $FUZZER $SUT_BASEPATH/$SUT/$sut_build_type $OUTPUT_BASEPATH/$output_dir $RUN $core_start $TIMEOUT $ROUND_TIME $*
}

in_round (){
    sut_build_type=$1
    shift
    core_start=$1
    shift

    scheduling_date=$(date +%F)

    in_round_w_named_output $sut_build_type $core_start "$SUT"_scheduled"$scheduling_date"_"$sut_build_type" $*
}

ROUND_COUNTER=0

COUNTER_OFFSET=0
TIMEOUT="5m"
DELTA="5"
RUN="5"



TIME_UNIT=$(convert_to_minutes $TIMEOUT)
TIME_UNIT=$(($TIME_UNIT+$DELTA))

OUTPUT_BASEPATH=~/osvaldo_tmp/outputs
SUT_BASEPATH=~/osvaldo_tmp/sut-docker/v0.2.6tmp6-aflppdouble-dbgv

# #             fuzzing-engine   fuzzer       fuzz_dir                          out_dir_prefx                                run core_start timeout  min_start additional_options
# #perform_task afl|libafl       fuzz_pdfload ~/sut-docker/xpdf-v4.00/baseline/ ~/outputs/pdfload-xpdf-v4.00_baseline-cmplog 5   0          5m       1         -c
# perform_task $ROUND_TYPE $ROUND_FUZZER $SUT_BASEPATH/$ROUND_SUT/aflpp                     $OUTPUT_BASEPATH/"$ROUND_SUT"_aflpp         $RUN 0 $TIMEOUT $ROUND_TIME 
# perform_task $ROUND_TYPE $ROUND_FUZZER $SUT_BASEPATH/$ROUND_SUT/aflppdouble_enumetric     $OUTPUT_BASEPATH/"$ROUND_SUT"_enumetric     $RUN 1 $TIMEOUT $ROUND_TIME 
# perform_task $ROUND_TYPE $ROUND_FUZZER $SUT_BASEPATH/$ROUND_SUT/aflppdouble_enumetric++   $OUTPUT_BASEPATH/"$ROUND_SUT"_enumetric++   $RUN 2 $TIMEOUT $ROUND_TIME 
# perform_task $ROUND_TYPE $ROUND_FUZZER $SUT_BASEPATH/$ROUND_SUT/aflppdouble_enumetricbb++ $OUTPUT_BASEPATH/"$ROUND_SUT"_enumetricbb++ $RUN 3 $TIMEOUT $ROUND_TIME 

next_round() {
    ROUND_TIME=$((TIME_UNIT * $ROUND_COUNTER))
    ((ROUND_COUNTER++))
    PRIVILEGED="0"
    MULTIDESOCK="0"
    FUZZ_PORT=0
}

all_of_one_kind(){
    next_round
    FUZZING_ENGINE=$1

    SUT=bison-3.3-forkmode_cmplog
    FUZZER=bison
    in_round $2 64 "@@" -o /dev/null

    SUT=bloaty-2020-05-25_cmplog
    FUZZER=fuzz_target
    in_round $2 69

    SUT=curl-aab3a7_cmplog
    FUZZER=curl_fuzzer
    in_round $2 74

    SUT=exiv2-0.26-forkmode_cmplog
    FUZZER=exiv2
    in_round $2 79 "@@"

    SUT=exiv2-0.27.1-forkmode_cmplog
    FUZZER=exiv2
    in_round $2 84 "@@"

    SUT=graphicsmagick-1.3.31-forkmode_cmplog
    FUZZER=gm
    in_round $2 89 convert "@@" /dev/null

    SUT=libtiff-3.9.7-forkmode_cmplog
    FUZZER=tiffsplit
    in_round $2 94 "@@"

    SUT=libxml2-v2.9.2-persistent_cmplog
    FUZZER=xml
    in_round $2 99

    SUT=ncurses-6.1-forkmode_cmplog
    FUZZER=infotocap
    in_round $2 104 -o /dev/null "@@"

    SUT=pcapplusplus-a817631_cmplog
    FUZZER=FuzzTarget
    in_round $2 109

    SUT=xpdf-4.00-forkmode_cmplog
    FUZZER=pdftotext
    in_round $2 114 "@@" /dev/null

    SUT=xpdf-4.00-persitent_cmplog
    FUZZER=fuzz_pdfload
    in_round $2 119
}


#all_of_one_kind afl  aflpp
#all_of_one_kind afl enumetric
#all_of_one_kind afl enumetric++
all_of_one_kind afl enumetricbb++
#all_of_one_kind afl enumetric_full
