#!/bin/bash -eu
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

echo "Precompiling AFLplusplus"

apt install -y llvm-13-dev

pushd $SRC/aflplusplus > /dev/null
make clean
# Unset CFLAGS and CXXFLAGS while building AFL since we don't want to slow it
# down with sanitizers.
SAVE_CXXFLAGS=$CXXFLAGS
SAVE_CFLAGS=$CFLAGS
unset CXXFLAGS
unset CFLAGS
export AFL_IGNORE_UNKNOWN_ENVS=1
export LLVM_CONFIG=llvm-config-13
make clean
AFL_NO_X86=1 PYTHON_INCLUDE=/ LLVM_CONFIG=llvm-config-13 make source-only
make -C utils/aflpp_driver

popd > /dev/null

export CXXFLAGS=$SAVE_CXXFLAGS
export CCFLAGS=$SAVE_CFLAGS

echo "Done."