#!/bin/bash 

sysctl -w vm.mmap_rnd_bits=28

export PATH=$OUT:$PATH
cd $OUT

FUZZER=$1
shift

QUEUE_TEST_CASE=$FUZZ_OUT/queue/*
CRASHES=$FUZZ_OUT/crashes/
# Ensure timeout is a bit larger than 1sec as some of the OSS-Fuzz fuzzers
# are slower than this.
LIBAFL_FUZZER_ARGS="-t 5000"

CMD_LINE_CCOV_ECOV="$OUT/$FUZZER $LIBAFL_FUZZER_ARGS -o $FUZZ_OUT -d -r -m $QUEUE_TEST_CASE"

CMD_CCOV_MERGE="llvm-profdata-13 merge $OUT/default.profraw -o $OUT/default.profdata" 
CMD_CCOV_EXPORT="llvm-cov-13 export --format=text --instr-profile $OUT/default.profdata $OUT/$FUZZER > $FUZZ_OUT/llvmcov.json"

# afltriage -i $CRASHES -o $FUZZ_OUT/afltriageout -t 15000 -- $OUT/$FUZZER @@
# afltriage -i $CRASHES -o $FUZZ_OUT/afltriageout-first_5_frames --bucket-strategy first_5_frames -t 15000 -- $OUT/$FUZZER @@
# afltriage -i $CRASHES -o $FUZZ_OUT/afltriageout-first_frame --bucket-strategy first_frame -t 15000 -- $OUT/$FUZZER @@

CMD_LINE_DEDUP_CRASH_5="afltriage -i $CRASHES -o $FUZZ_OUT/afltriageout-first_5_frames --bucket-strategy first_5_frames -t 15000 -- $DEDUP_BUILD/$FUZZER @@"
CMD_LINE_DEDUP_CRASH_1="afltriage -i $CRASHES -o $FUZZ_OUT/afltriageout-first_frame --bucket-strategy first_frame -t 15000 -- $DEDUP_BUILD/$FUZZER @@"

pushd $FUZZ_OUT
unzip  fuzz_out.zip
rm fuzz_out.zip
popd

if [[ ! -s $FUZZ_OUT/llvmcov.json ]] || [[ ! -d $FUZZ_OUT/afltriageout-first_5_frames ]] || [[ ! -d $FUZZ_OUT/afltriageout-first_frame ]]; then

    if [[ ! -f $FUZZ_OUT/queue-preanalysis ]] ; then

        #check for element in queue that will lock
        for element in $QUEUE_TEST_CASE; do
            timeout 5 $OUT/$FUZZER -o $FUZZ_OUT $element
            ret=$?
            if [ $ret -eq 124 ] ; then
                mkdir -p $FUZZ_OUT/timeout-queue/
                mv $element $FUZZ_OUT/timeout-queue/
            fi 

            if [ $ret -ne 0 ] ; then
                mkdir -p $FUZZ_OUT/crashes-queue/
                mv $element $FUZZ_OUT/crashes-queue/
            fi 
        done

    fi

    touch $FUZZ_OUT/queue-preanalysis

    bash -c "$CMD_LINE_CCOV_ECOV"
fi

if [[ ! -s $FUZZ_OUT/llvmcov.json ]]; then
    bash -c "$CMD_CCOV_MERGE"
    bash -c "$CMD_CCOV_EXPORT"
fi

mv $CRASHES/.*.metadata /..
mv $CRASHES/.*.lafl_lock /..
if [[ ! -d $FUZZ_OUT/afltriageout-first_5_frames ]]; then
    bash -c "$CMD_LINE_DEDUP_CRASH_5"
fi

if [[ ! -d $FUZZ_OUT/afltriageout-first_frame ]]; then
    bash -c "$CMD_LINE_DEDUP_CRASH_1"
fi
mv ../.*.metadata $CRASHES
mv ../.*.lafl_lock $CRASHES

cd $FUZZ_OUT
cp fuzzer_stats.csv fuzzer_stats.csv.bk
zip -r fuzz_out.zip ./queue ./crashes ./fuzzer_stats.csv
mv ./fuzzer_stats.csv.bk ./fuzzer_stats.csv